### ISSUE TITLE
How would can I set-up a GitLab CI/CD workflow with share runners

### ISSUE THREAD

**Issue by graugans** [IARSystems/bx-gitlab-ci#2]
Is there a way to set-up a Docker Container to be used in a private GitLab instance using shared runners? I wantto avaoid to set-up a dedicated Linux Machine only for the IAR development. I konw there is the [bx Docker image](https://github.com/IARSystems/bx-docker) example but it uses a volume to deal with the license. Which again will be a pain to set-up in a shared runner environment.

**Comment by felipe-iar** [comment]
Firstly, thank you for your question.

Right now, I am unaware of any particular reason why GitLab and Docker could not co-exist in a single server. In theory, it should be possible to combine the solutions we have presented on our CI-related tutorials at GitHub the way you did.

Our current [bx-docker](https://github.com/iarsystems/bx-docker) scripts use Docker Volumes for caching the IAR License Management System (LMS2) license tokens. The way the License System currently works requires caching of those tokens on a per-`$DOCKER_HOST` basis.

From such a perspective, using (or not using) Docker Volumes should not matter for each `$DOCKER_HOST`. Either way, license tokens created for one `$DOCKER_HOST` cannot be reused by a different machine in the network. From the license server perspective, those will be treated as "new requests". 

The `bx-docker` tutorial evolved over time thanks to the feedback provided by customers like you. If volumes pose a problem for the use case, you might want to check the [previous version of bx-docker](https://github.com/IARSystems/bx-docker/tree/8570e369f4f9807114214531d286ffb69ae4e158)  where we used to store the tokens direcly in the underlying host.

Let us know if you have further questions.

**Comment by graugans** [comment]
> Firstly, thank you for your question.
> 
> Right now, I am unaware of any particular reason why GitLab and Docker could not co-exist in a single server. In theory, it should be possible to combine the solutions we have presented on our CI-related tutorials at GitHub the way you did.

I am not sure if I have explained our use-case very well. We have a private GitLab server. This uses a bunch of shared runners. Those runners are pulling Docker images for the builds. So we have like 10 Runners on which the Docker image can be executed.

> Our current [bx-docker](https://github.com/iarsystems/bx-docker) scripts use Docker Volumes for caching the IAR License Management System (LMS2) license tokens. The way the License System currently works requires caching of those tokens on a per-`$DOCKER_HOST` basis.
> 
> From such a perspective, using (or not using) Docker Volumes should not matter for each `$DOCKER_HOST`. Either way, license tokens created for one `$DOCKER_HOST` cannot be reused by a different machine in the network. From the license server perspective, those will be treated as "new requests".

I am not familiar with the license managment of IAR. Is there a possibility to release a license request? In the document you linked below I do read:

`the Host license setup will need to be run every time after the Host reboots.`

This would be similar if I just request the License as part of the pipeline and use the GitLab caching to convey the license token. But if this will lead to all licenses occuipied it will be a bad design.

> The `bx-docker` tutorial evolved over time thanks to the feedback provided by customers like you. If volumes pose a problem for the use case, you might want to check the [previous version of bx-docker](https://github.com/IARSystems/bx-docker/tree/8570e369f4f9807114214531d286ffb69ae4e158) where we used to store the tokens direcly in the underlying host.
> 
> Let us know if you have further questions.

**Comment by felipe-iar** [comment]
>I am not sure if I have explained our use-case very well. We have a private GitLab server. This uses a bunch of shared runners. Those runners are pulling Docker images for the builds. So we have like 10 Runners on which the Docker image can be executed.

It should be fine to have a central Docker Registry for pulling pre-built images to the build server with the runner. If the 10 runners (containerized or not) are on the same build server (node/instance), the IAR LMS2 license tokens locks to the underlying machine and can be shared across the [N] containers. The `lightlicensemanager setup` has to be performed only once per build server to point to the license server.

>I am not familiar with the license managment of IAR. Is there a possibility to release a license request? In the document you linked below I do read:
>`the Host license setup will need to be run every time after the Host reboots.`

That was a note created because some customers were redirecting the license configuration folder (`$IAR_LMS_SETTINGS_DIR`, defaults to `/usr/local/etc/IARSystems` if not overriden) to volatile memory (`/tmp`). The configuration folder holds 2 different things: 1) the initial setup to point to the license server 2) cached token lease, specific to the requesting machine. In the `/tmp` scenario, the initial license configuration would be lost after a power cycle, requiring the client-side to be set up again. Under that circunstance, a script could re-run the initial setup at boot. That is possible but not recommended.

>This would be similar if I just request the License as part of the pipeline and use the GitLab caching to convey the license token. But if this will lead to all licenses occuipied it will be a bad design.

As mentioned before, caching the initial license configuration should potentially work. The key concept to keep in mind is that  the tokens are automatically requested to the license server which was specified during the initial setup. After that, the license lease tokens are requested automatically by the client for any action that requires it.

In case you want to discuss non-public details regarding your particular setup, we are also available at fae.emea@iar.com.

**Comment by graugans** [comment]
> > I am not sure if I have explained our use-case very well. We have a private GitLab server. This uses a bunch of shared runners. Those runners are pulling Docker images for the builds. So we have like 10 Runners on which the Docker image can be executed.
> 
> It should be fine to have a central Docker Registry for pulling pre-built images to the build server with the runner. If the 10 runners (containerized or not) are on the same build server (node/instance), the IAR LMS2 license token locks to the underlying machine and can be shared across the [N] containers. The `lightlicensemanager setup` has to be performed only once per build server to point to the license server.

The 10 nodes are distinct machines which are themselves are subject of change. This allows us to add and remove machines on a dynamic scale. If one fails it is quite easy to remove it and add a new machine instead. Or if more runners are needed to cope with the workload this can be added.
 
> > I am not familiar with the license managment of IAR. Is there a possibility to release a license request? In the document you linked below I do read:
> > `the Host license setup will need to be run every time after the Host reboots.`
> 
> That was a note created because some customers were redirecting the license configuration folder (`$IAR_LMS_SETTINGS_DIR`, defaults to `/usr/local/etc/IARSystems` if not overriden) to volatile memory (`/tmp`). The configuration folder holds 2 different things: 1) the initial setup to point to the license server 2) cached token lease, specific to the requesting machine. In the `/tmp` scenario, the initial license configuration would be lost after a power cycle, requiring the client-side to be set up again. Under that circunstance, a script could re-run the initial setup at boot. That is possible but not recommended.

Okay, that make sense. I guess I got it now.
> 
> > This would be similar if I just request the License as part of the pipeline and use the GitLab caching to convey the license token. But if this will lead to all licenses occuipied it will be a bad design.
> 
> As mentioned before, caching the initial license configuration should potentially work. The key concept to keep in mind is that the token request is automatically sent to the license server which was specified during the initial setup. After that, the license lease tokens are requested automatically by the client for any action that requires it.

Okay in this case it is kind of node locked, I guess the easiest thing will be to have a dedicated node which provides the caching to the Docker image. Which can be modeled by additional tags. The set-up can be performed by ansible scripts.
> 
> In case you want to discuss non-public details regarding your particular setup, we are also available at [fae.emea@iar.com](mailto:fae.emea@iar.com).

I guess I do have all information needed for the moment. I have to get in touch with the IT department and the development team to see if we do have the appropriate license and services up and running.

Thanks for your time
